# Generated by Django 5.0.7 on 2024-07-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={"verbose_name_plural": "crews"},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"verbose_name_plural": "routes"},
        ),
        migrations.AlterModelOptions(
            name="station",
            options={"ordering": ["name"], "verbose_name_plural": "stations"},
        ),
        migrations.AlterModelOptions(
            name="train",
            options={"ordering": ["number"], "verbose_name_plural": "trains"},
        ),
        migrations.AlterModelOptions(
            name="traintype",
            options={"verbose_name_plural": "train_types"},
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["name"],
                name="station_sta_name_7e5a06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="station",
            index=models.Index(
                fields=["latitude", "longitude"],
                name="station_sta_latitud_9644e0_idx"
            ),
        ),
    ]
