# Generated by Django 5.0.7 on 2024-07-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_alter_crew_options_alter_route_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name_plural": "facilities",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="train",
            name="facilities",
            field=models.ManyToManyField(
                blank=True, related_name="trains", to="station.facility"
            ),
        ),
    ]
